### ISSUE TITLE
Improve memory diagnostics

### ISSUE THREAD

**Issue by glyn** [cloudfoundry/jvmkill#12]
It would be helpful to identify memory pools which have reached their maximum values and, for each of them, print a diagnostic message naming the memory pool (in user understandable terms) together with a hint about how to fix the problem.

See [this google doc](https://docs.google.com/document/d/1IA26pZ8XsUSnQHZ5bEQ_2-Ihr3GdWH4jr-SW81XtNM8/edit) for a draft design.

**Comment by glyn** [comment]
@youngm I've given you comment access to the doc if you'd be kind enough to review it.

**Comment by youngm** [comment]
@glyn I think the proposal looks great.

**Comment by youngm** [comment]
@glyn I finally got some time to dig into https://github.com/cloudfoundry/jvmkill/issues/10 a little more.

I did some OOM testing and discovered that when Heap runs out I do see a "Resource exhaustion event" message.  However, if I run out of MetaSpace or CompressedClassSpaceSize The only message I see in the logs is the: `ResourceExhausted! (1/0)` log line.

Just thought I'd make you aware of that finding as you work through this issue.

**Comment by glyn** [comment]
Thanks @youngm. I re-opened #10 with that info.

**Comment by glyn** [comment]
@nebhale & @youngm I've updated the google doc with my latest thinking. I am allowing for the likelihood that compressed class space is included in metaspace. See https://github.com/cloudfoundry/java-buildpack/issues/499#issuecomment-340779211 for further analysis.

**Comment by nebhale** [comment]
The log messages look good from my end.  I get that they're a bit redundant (sitting so close to the actual numbers) but given that in most cases we're looking at 10+ character numbers, it's easy to gloss over the values themselves.  Keeping the message close encourages you to look with detail.

**Comment by youngm** [comment]
It can also be hard to read all that when loggregator has mixed up the lines.  Having a useful hint there on a single line could help sort out the problem when things get mixed up.  I'm good with it.

**Comment by nebhale** [comment]
@glyn Google Doc with hints looks good.

**Comment by glyn** [comment]
Implemented in 7dbc0acfde9e1867ffb.
