### ISSUE TITLE
`cargo test --all` crashes macOS High Sierra

### ISSUE THREAD

**Issue by glyn** [cloudfoundry/jvmkill#14]
This occurred at commit 8bbbb4322e on macOS 10.13.4 with rust 1.24.0.

Also happens with rust 1.25.0.

This is reminiscent of https://github.com/cloudfoundry/jvmkill/issues/11.

**Comment by glyn** [comment]
I experimented with `setrlimit(RLIMIT_NPROC, n)` for various values of `n`. I couldn't find a value which made the tests pass but prevented macOS from crashing.

**Comment by glyn** [comment]
The macOS CI is running Sierra, so this behaviour seems to have been introduced by High Sierra.

**Comment by nebhale** [comment]
Later versions of rust on High Sierra seem to have solved this.
