### ISSUE TITLE
CI tests fail: libjvmkill.so not found

### ISSUE THREAD

**Issue by glyn** [cloudfoundry/jvmkill#15]
CI builds in the last day are failing with:
```
Error occurred during initialization of VM
Could not find agent library /tmp/build/80754af9/jvmkill/target/debug/build/libloading-b7cd85c1ea1c2903/out/libjvmkill.so in absolute path, with error: /tmp/build/80754af9/jvmkill/target/debug/build/libloading-b7cd85c1ea1c2903/out/libjvmkill.so: cannot open shared object file: No such file or directory
```

Builds [40](https://java-experience.ci.springapps.io/teams/java-experience/pipelines/jvmkill/jobs/test-trusty/builds/40) through [43](https://java-experience.ci.springapps.io/teams/java-experience/pipelines/jvmkill/jobs/test-trusty/builds/43) failed with these symptoms.

**Comment by glyn** [comment]
Looking in the container of the failed build step, the directory `/tmp/build/80754af9/jvmkill/target/debug/build/libloading-b7cd85c1ea1c2903/out/` contained `libglobal_static.a`, a static library, but not `libmjvmkill.so` which wouldbe a shared object (dynamic) library.

**Comment by glyn** [comment]
The failure occurs with rust 0.26.0. The previous successful run was in mid February 2018 which was based on a docker image built around the same time which presumably used rust 0.25.0. Perhaps this is a change in behaviour between 0.25.0 and 0.26.0.

Next step - try to reproduce in a Trusty VM.

**Comment by nebhale** [comment]
@glyn The problem is [this line](https://github.com/cloudfoundry/jvmkill/blob/master/jvmkill-tests/tests/common/mod.rs#L61):

```rust
let root = PathBuf::from(env::var("LD_LIBRARY_PATH").or(env::var("DYLD_LIBRARY_PATH")).unwrap().split(":").next().unwrap());
```

We're blindly assuming that the root directory where the `libjvmkill.[so|dylib]` is located is the first folder on the library path.  Seems like we're going to have to iterate over the collection of directories looking for the library and only once we've actually found it, return that value.

Let's see if I can now learn enough Rust to implement that...

**Comment by glyn** [comment]
@nebhale Nice theory. Have you confirmed it? If you don't want to bother with the Rust, I can look into that tomorrow.

**Comment by nebhale** [comment]
Not confirmed yet, but quite confident, and I'll let you know if I can't bend Rust to my will.

**Comment by nebhale** [comment]
Well, that fixed the "cannot find agent" problem, but there's now a legit failure that follows.

**Comment by nebhale** [comment]
The failing output https://gist.github.com/nebhale/d95c3c544e70fea244eac0b909217acd

**Comment by glyn** [comment]
The problem seems to be that the expected output:
```
ResourceExhausted! (1/2)
```
was not found in the output:
```
ResourceExhausted! (1/OpenJDK 64-Bit Server VM warning: 2)
```

**Comment by glyn** [comment]
Looking at the code that writes the `ResourceExhausted!` message, it looks like the text `OpenJDK 64-Bit Server VM warning: ` was output from the JVM and was interspersed with output from `jvmkill`. The test output shows the context:
```
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 12288 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /tmp/build/80754af9/jvmkill/jvmkill-tests/hs_err_pid99708.log

:OUTPUT
OUTPUT:
OpenJDK 64-Bit Server VM warning: Attempt to protect stack guard pages failed.
OpenJDK 64-Bit Server VM warning: Attempt to deallocate stack guard pages failed.

Resource exhaustion event: the JVM was unable to create a thread.
ResourceExhausted! (1/OpenJDK 64-Bit Server VM warning: 2)

The JVM is about to throw a java.lang.OutOfMemoryError.
INFO: os::commit_memory(0x00007feda8564000, 12288, 0) failed; error='Cannot allocate memory' (errno=12)
```
The only solution I can think of is to avoid the JVM hitting the error committing reserved memory, either by increasing the amount of reserved memory available or reducing the consumption of reserved memory in the tests.

I am experimenting with calling `setrlimit` with `RLIMIT_NPROC` to set the maximum number of simultaneous processes for the current user id as this may cause the test to run out of threads before running out of reserved memory.

**Comment by glyn** [comment]
According to [https://bugs.openjdk.java.net/browse/JDK-8187709](JDK-8187709), native memory allocation errors can be reduced by setting `-XX:-UseCompressedOops`. I'm going to try that.
