### ISSUE TITLE
Memory Summary is not printed on OOM

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/jvmkill#6]
It would [appear](https://gist.github.com/nebhale/12aadcad1ba41a31b3cabc0bca78c968#file-missing-memory-log-L192-L193) that the memory summary isn't printed on OoM.  I notice the `exit 137` which is the container killing the current process.  It's only a second after the OoM so I don't think it's a timing issue.  I wonder if `jvmkill` is actually busting the container memory limit when it reaches out for MBeans.

Because all of this happens so close to the end of the JVM, I think we should probably ensure flushes of the `std*` streams before the `jvmkill` takes down the process for sure.  Once we've got that, it'd be good to see if we can diagnose whether making those calls is occupying enough memory that we provoke the container.  If that's the case, maybe we update the memory calculator to leave 1% (or 0.5%, etc) for `jvmkill` to do its thing.

**Comment by glyn** [comment]
Another [example](https://gist.github.com/glyn/92172606bf77a1408e2c08cd45133638) shows the following logs produced by jvmkill:
```
2017-03-20T09:10:32.91+0000 [APP/PROC/WEB/0]OUT | 300            | 7200        | Ljava/util/concurrent/CopyOnWriteArrayList;                                                                      |
2017-03-20T09:10:32.99+0000 [APP/PROC/WEB/0]ERR Killing current process
2017-03-20T09:10:33.03+0000 [APP/PROC/WEB/0]OUT | 22Exit status 137
```

"Killing current process" is logged to standard error by jvmkill just before killing the JVM with SIGKILL (9). This is consistent with the process exiting with status code 137 (=128+9). So the OOM killer is not necessarily involved here.

**Comment by glyn** [comment]
It turned out that the memory summary was not being flushed properly. Adding flushing and some sleeps to avoid over-exerting loggregator produced the [correct output](https://gist.github.com/glyn/60039c3c0a05d74b16dd58caf94cb7ac).
